import "./globals.css";
import Header from "./header";
import Footer from "./footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header/>
        {children}
      <Footer/>
      </body>
    </html>
  );
}
