import "@/app/globals.css";
import { AppProvider } from "@/app/appContext";

export const metadata = {
  title: "CalorieAI",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <AppProvider>
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
    </AppProvider>
  );
}
