import "@/app/globals.css";
import { AppProvider } from "@/app/appContext";

export const metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};
export default function DashboardLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}